server:
  port: 9200
spring:
  cloud:
    function:
      definition: notificationOrder
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost:9092,localhost:9094

      bindings:
        notificationOrder-in-0:
          destination: notificationTopic
          group: my-notification-group
          content-type: application/json
          consumer:
            use-native-decoding: false
  mongodb:
    uri: mongodb://localhost:27017/notificationsms

logging:
  level:
    org.springframework.cloud.stream: DEBUG
    org.springframework.kafka: DEBUG
