server:
#  #port: 9100
  port: 0
spring:
  application:
    name: orders-service
  cloud:
    function:
      definition: produceOrder
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost:9092,localhost:9094
#          configuration:
#            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
#            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer

      bindings:
        # ? Producer binding
        produceOrder-out-0:
          destination: notificationTopic
          content-type: application/json

#        # ? Consumer binding
#        produceOrder-in-0:
#          destination: my-topic
#          group: my-order-group
#          content-type: text/plain
  mongodb:
    uri: mongodb://localhost:27017/ordersms

logging:
  level:
    org.springframework.cloud.stream: DEBUG
    org.springframework.kafka: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true